version: "3.9"
services: 
  auth-service:
    build: auth-service
    ports: 
      - "3001:9000"
      - "3002:9090"
    env_file:
      - auth-service/.env
    networks:
      default:
        aliases:
          - auth-service
  users-service:
    build: users-service
    ports:
      - "3003:9090"
    env_file:
      - users-service/.env
  file-info-service:
    build: file-info-service
    ports:
      - "3004:9000"
      - "3005:9090"
    env_file:
      - file-info-service/.env
  fs-service:
    build: fs-service
    ports:
      - "3006:9090"
    env_file:
      - fs-service/.env
      
networks:
  default:
    external: true
    name: raspstore-network