version: "3.9"
services: 
  auth:
    build: idp
    ports: 
      - "3001:9000"
      - "3002:9090"
    env_file:
      - idp/.env.docker
    networks:
      default:
        aliases:
          - idp
  file-info:
    build: file-info-service
    ports:
      - "3005:9000"
      - "3006:9090"
    env_file:
      - file-info-service/.env.docker
  fs:
    build: fs-service
    ports:
      - "3007:9090"
    env_file:
      - fs-service/.env
networks:
  default:
    external: true
    name: raspstore-network
