version: "3.9"
services: 
  auth:
    build: auth-service
    ports: 
      - "3001:9000"
      - "3002:9090"
    env_file:
      - auth-service/.env
    networks:
      default:
        aliases:
          - auth-service
  users:
    build: users-service
    ports:
      - "3003:9000"
      - "3004:9090"
    env_file:
      - users-service/.env.docker

  file-info:
    build: file-info-service
    ports:
      - "3005:9000"
      - "3006:9090"
    env_file:
      - file-info-service/.env.docker
  fs:
    build: fs-service
    ports:
      - "3007:9090"
    env_file:
      - fs-service/.env
networks:
  default:
    external: true
    name: raspstore-network
