// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/facade/user.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/facade/user.go -destination=internal/application/facade/mocks/user.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/murilo-bracero/raspstore/file-service/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserFacade is a mock of UserFacade interface.
type MockUserFacade struct {
	ctrl     *gomock.Controller
	recorder *MockUserFacadeMockRecorder
}

// MockUserFacadeMockRecorder is the mock recorder for MockUserFacade.
type MockUserFacadeMockRecorder struct {
	mock *MockUserFacade
}

// NewMockUserFacade creates a new mock instance.
func NewMockUserFacade(ctrl *gomock.Controller) *MockUserFacade {
	mock := &MockUserFacade{ctrl: ctrl}
	mock.recorder = &MockUserFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFacade) EXPECT() *MockUserFacadeMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockUserFacade) Save(user *model.CreateUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserFacadeMockRecorder) Save(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserFacade)(nil).Save), user)
}
