database:
  uri: {{ envOrKey "MONGO_URI" "" }}
  name: {{ envOrKey "MONGO_DATABASE_NAME" "rstore" }}

server:
  port: {{ envOrKey "SERVER_PORT" "8080" }}
  storage:
    path: {{ envOrKey "STORAGE_PATH" "~/.rstore/strg" }}
    limit: {{ envOrKey "STORAGE_LIMIT" "1G" }}

auth:
  certURI: {{ envOrKey "AUTH_CERT_URI" "" }} 