storage:
  path: {{ envOrKey "STORAGE_PATH" "~/.rstore" }}
  limit: {{ envOrKey "STORAGE_LIMIT" "1G" }}

server:
  read-header-timeout: {{ envOrKeyInt "READ_HEADER_TIMEOUT" 3 }}
  port: {{ envOrKey "SERVER_PORT" "9090" }}

auth:
  enable-pam: {{ envOrKeyBoolean "RS_ENABLE_PAM" true }}
  public-key-url: {{ envOrKey "PUBLIC_KEY_URL" "" }}
