openapi: 3.0.3
info:
  title: Raspstore File Service
  description: Microservice REST specification of file-service endpoints.
  contact:
    email: soon@todo.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:9090/file-service
tags:
  - name: files
    description: File Metadata workflow
  - name: upload
    description: Upload a file
  - name: download
    description: Download a file

paths:
  /v1/files:
    get:
      tags:
        - files
      summary: Get All File Metadata from logged in user
      description: |- 
        Get all file metadata based on parameters and accessToken provided.
        This can only be done by the logged in user.
        
        Secret files will only be sent when the query parameter "secret" is set to true.
      operationId: findAllFileInfoByLoggedUser
      parameters:
        - $ref: '#/components/parameters/PageQueryParameter'
        - $ref: '#/components/parameters/SizeQueryParameter'
        - $ref: '#/components/parameters/FilenameQueryParameter'
        - $ref: '#/components/parameters/SecretQueryParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessFileMetadataListResponse'
        '500':
          description: Internal Server Error
  /v1/files/{fileId}:
    put:
      tags:
        - files
      summary: Update file metadata
      description: |- 
        Update file metadata. 
        This action can only be done by the logged in user.
        
        If "secret" tag is true, viewers/editors are ignored.
      operationId: updateFileMetadata
      parameters:
        - $ref: '#/components/parameters/FileIdPathParameter'
      requestBody:
        $ref: '#/components/requestBodies/UpdateFileMetadataRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessUpdateFileMetadataResponse'
        '400':
          $ref: '#/components/responses/BadRequestUpdateFileMetadataResponse'
        '404':
          description: file info with provided id not found
        '409':
          description: file with provided info already exists
        '500':
          description: Internal Server Error
    delete:
      tags:
        - files
      summary: Delete file
      description: |- 
        Removes file metadata and the file itself from the system.
        
        This can only be done by the logged in user, that should be the owner of
        the file and cannot be undone.
      operationId: deleteFile
      parameters:
        - $ref: '#/components/parameters/FileIdPathParameter'
      responses:
        '204':
          description: File removed successfully
        '400':
          description: Invalid fileId
        '404':
          description: File not found
        '500':
          description: Internal Server Error
  /v1/uploads:
    post:
      tags:
        - upload
      summary: Upload File
      description: |-
        Upload file to server. This can only be done by the logged in user.
      operationId: fileUpload
      requestBody:
        $ref: '#/components/requestBodies/UploadFileRequest'
      responses:
        '204':
          description: 'File uploaded successfully'
        '400':
          $ref: '#/components/responses/BadRequestFileUpload'
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
  /v1/downloads/{fileId}:
    get:
      tags:
        - download
      summary: Download file
      description: |-
        Download file that logged in user has access.
        This action can only be done by the logged in user.
      operationId: downloadFile
      parameters:
        - $ref: '#/components/parameters/FileIdPathParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessFileResponse'
        '401':
          description: Unauthorized
        '404':
          description: file info with provided id not found
        '500':
          description: Internal Server Error
components:
  schemas:
    UploadFileRepresentation:
      type: object
      properties:
        file:
          type: string
          format: binary
    UserInfoRepresentation:
      type: object
      properties:
        userId:
          type: string
          example: 63d14f9e9f76d34fa3b0a4a1
        username:
          type: string
          example: cool-username
    FileMetadataRepresentation:
      type: object
      properties:
        fileId:
          type: string
          example: 507f1f77bcf86cd799439011
        filename:
          type: string
          example: file.txt
        size:
          type: number
          format: int64
          example: 1024
        secret:
          type: boolean
        owner:
          type: string
          example: 63d14edc2f4ee7bec256515b
          description: |-
            User representation of the owner of the file. 
            There can exists only one owner per file
        editors:
          type: array
          items:
            $ref: '#/components/schemas/UserInfoRepresentation'
          example:
            - userId: 63d1539be80b85c273d612e4
              username: karl
            - userId: 63d153b097e145d528a1bfbf
              username: johndoe1
        viewers:
          type: array
          items:
            $ref: '#/components/schemas/UserInfoRepresentation'
        createdBy:
          $ref: '#/components/schemas/UserInfoRepresentation'
        updatedBy:
          $ref: '#/components/schemas/UserInfoRepresentation'
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
    PageRepresentation:
      type: object
      properties:
        size:
          type: integer
          example: 10
        totalElements:
          type: integer
          example: 10
        page:
          type: integer
          example: 1
        next:
          type: string
          example: 'http://localhost:9000/file-info-service/files?page=2&size=10'
    UpdateFileMetadataRepresentation:
      type: object
      properties:
        filename:
          type: string
          example: coolfile.bpm
        secret:
          type: boolean
        editors:
          type: array
          items:
            type: string
            example: 63d150ccd80a557126f07299
          example: [63d1512264ad3b195c19d8d2, 63d151299970181cc3adcaf1]
        viewers:
          type: array
          items:
            type: string
            example: 63d150ff46156f7cf0c54e1b
          example: [63d1510e09ca8779e148c45c, 63d15115460f5f0da06df1a5]
    ApiErrorException:
      type: object
      properties:
        code:
          type: string
          example: 'ERR010'
        message:
          type: string
          example: 'Field email must not be null or empty'
        traceId:
          type: string
          example: 'df438c36-9aa4-11ed-a8fc-0242ac120002'
  requestBodies:
    UploadFileRequest:
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/UploadFileRepresentation'
    UpdateFileMetadataRequest:
      description: |- 
        File Metadata request object required to update a existing file info
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateFileMetadataRepresentation'
  parameters:
    FilenameQueryParameter:
      name: filename
      in: query
      schema:
        type: string
        example: cv.pdf
    PageQueryParameter:
      name: page
      required: true
      in: query
      schema:
        type: integer
        example: 1
    SizeQueryParameter:
      name: size
      required: true
      in: query
      schema:
        type: integer
        example: 1
    SecretQueryParameter:
      name: secret
      in: query
      schema:
        type: boolean
    FileIdPathParameter:
      name: fileId
      in: path
      required: true
      schema:
        type: string
        example: 63d14dfdec04b7ba9c2372f5
    
  responses:
    BadRequestFileUpload:
      description: payload invalid or malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorException'
    SuccessFileResponse:
      description: File retrieved successfully
      content:
        application/octet-stream:
          schema:
            type: string
            example: file binary
    SuccessUpdateFileMetadataResponse:
      description: File metadata updated successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FileMetadataRepresentation'
    BadRequestUpdateFileMetadataResponse:
      description: payload invalid or malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorException'
    
    SuccessFileMetadataListResponse:
      description: List of file metadata object
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/PageRepresentation'
              - type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/FileMetadataRepresentation'
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []