// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: proto/v1/users-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserConfigurationRequest) Reset() {
	*x = GetUserConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_users_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConfigurationRequest) ProtoMessage() {}

func (x *GetUserConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_users_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetUserConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_users_service_proto_rawDescGZIP(), []int{0}
}

type UserConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageLimit            string `protobuf:"bytes,1,opt,name=StorageLimit,proto3" json:"StorageLimit,omitempty"`
	MinPasswordLength       int64  `protobuf:"varint,2,opt,name=MinPasswordLength,proto3" json:"MinPasswordLength,omitempty"`
	AllowPublicUserCreation bool   `protobuf:"varint,3,opt,name=AllowPublicUserCreation,proto3" json:"AllowPublicUserCreation,omitempty"`
	AllowLoginWithEmail     bool   `protobuf:"varint,4,opt,name=AllowLoginWithEmail,proto3" json:"AllowLoginWithEmail,omitempty"`
	EnforceMfa              bool   `protobuf:"varint,5,opt,name=EnforceMfa,proto3" json:"EnforceMfa,omitempty"`
}

func (x *UserConfiguration) Reset() {
	*x = UserConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_users_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfiguration) ProtoMessage() {}

func (x *UserConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_users_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfiguration.ProtoReflect.Descriptor instead.
func (*UserConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_v1_users_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserConfiguration) GetStorageLimit() string {
	if x != nil {
		return x.StorageLimit
	}
	return ""
}

func (x *UserConfiguration) GetMinPasswordLength() int64 {
	if x != nil {
		return x.MinPasswordLength
	}
	return 0
}

func (x *UserConfiguration) GetAllowPublicUserCreation() bool {
	if x != nil {
		return x.AllowPublicUserCreation
	}
	return false
}

func (x *UserConfiguration) GetAllowLoginWithEmail() bool {
	if x != nil {
		return x.AllowLoginWithEmail
	}
	return false
}

func (x *UserConfiguration) GetEnforceMfa() bool {
	if x != nil {
		return x.EnforceMfa
	}
	return false
}

var File_proto_v1_users_service_proto protoreflect.FileDescriptor

var file_proto_v1_users_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xf1, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x4d,
	0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x4d, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x17, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x41, 0x6c, 0x6c, 0x6f,
	0x77, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x13, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x13, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x4d, 0x66, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x45, 0x6e, 0x66, 0x6f, 0x72,
	0x63, 0x65, 0x4d, 0x66, 0x61, 0x32, 0x63, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x14, 0x67, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_users_service_proto_rawDescOnce sync.Once
	file_proto_v1_users_service_proto_rawDescData = file_proto_v1_users_service_proto_rawDesc
)

func file_proto_v1_users_service_proto_rawDescGZIP() []byte {
	file_proto_v1_users_service_proto_rawDescOnce.Do(func() {
		file_proto_v1_users_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_users_service_proto_rawDescData)
	})
	return file_proto_v1_users_service_proto_rawDescData
}

var file_proto_v1_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_users_service_proto_goTypes = []interface{}{
	(*GetUserConfigurationRequest)(nil), // 0: pb.GetUserConfigurationRequest
	(*UserConfiguration)(nil),           // 1: pb.UserConfiguration
}
var file_proto_v1_users_service_proto_depIdxs = []int32{
	0, // 0: pb.UserConfigService.getUserConfiguration:input_type -> pb.GetUserConfigurationRequest
	1, // 1: pb.UserConfigService.getUserConfiguration:output_type -> pb.UserConfiguration
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_users_service_proto_init() }
func file_proto_v1_users_service_proto_init() {
	if File_proto_v1_users_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_users_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_users_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_users_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_users_service_proto_goTypes,
		DependencyIndexes: file_proto_v1_users_service_proto_depIdxs,
		MessageInfos:      file_proto_v1_users_service_proto_msgTypes,
	}.Build()
	File_proto_v1_users_service_proto = out.File
	file_proto_v1_users_service_proto_rawDesc = nil
	file_proto_v1_users_service_proto_goTypes = nil
	file_proto_v1_users_service_proto_depIdxs = nil
}
