openapi: 3.0.3
info:
  title: Raspstore Authentication Service
  description: REST specification of auth-service microservice endpoints.
  contact:
    email: soon@todo.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:9000/idp/
tags:
  - name: auth
    description: Operations about authentication
  - name: user
    description: Operations about user
  - name: admin
    description: Admin operations 
paths:
  /v1/login:
    post:
      security:
        - loginAuth: []
      tags:
        - auth
      summary: Login
      description: |- 
        Uses Basic credentials sent in Authorization header and mfaToken
        (when enabled) to authenticate user against backend
      operationId: login
      requestBody:
        $ref: '#/components/requestBodies/LoginRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessLoginResponse'
        '400':
          $ref: '#/components/responses/BadRequestLoginResponse'
        '401':
          description: Username, password or mfa token invalid
        '500':
          description: Internal Server Error
  
  /v1/refresh:
    get:
      security:
        - cookieRefreshToken: []
      tags:
        - auth
      summary: Request a new JWT using provided refreshToken
      description: Sends refreshToken as HttpOnly cookie and validates it
      operationId: refreshJwtByToken
      responses:
        '200':
          $ref: '#/components/responses/SuccessRefreshResponse'
        '401':
          description: Refresh Token is invalid or inexistent
        '500':
          description: Internal Server Error

  /v1/profile:
    get:
      security: 
        - cookieAccessToken: []
        - headerAccessToken: []
      tags:
        - user
      summary: Get user profile
      description: Get user profile based on provided JWT on either Authorization header or access_token cookie
      operationId: getProfile
      responses:
        '200':
          $ref: '#/components/responses/SuccessUserProfileResponse'
        '401':
          description: JWT token is invalid, expired or inexistent
        '403':
          description: User account is inactive
        '500':
          description: Internal Server Error
    put:
      security:
        - cookieAccessToken: []
        - headerAccessToken: []
      tags:
        - user
      summary: Update user profile
      description: Update user profile based on provided JWT on either Authorization header or access_token cookie
      operationId: updateProfile
      requestBody:
        $ref: '#/components/requestBodies/UpdateProfileRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessUserProfileResponse'
        '400':
          $ref: '#/components/responses/BadRequestCreateUserResponse'
        '401':
          description: JWT token is invalid, expired or inexistent
        '403':
          description: User account is inactive
        '409':
          description: user with provided info already exists in database
        '500':
          description: Internal Server Error
    delete:
      security:
        - cookieAccessToken: []
        - headerAccessToken: []
      tags:
        - user
      summary: Delete user profile
      description: |-
        Delete user profile based on provided JWT on either Authorization header or access_token cookie.

        This action is irreversible
      operationId: deleteProfile
      responses:
        '204':
          description: No Content
        '401':
          description: JWT token is invalid, expired or inexistent
        '403':
          description: User account is inactive
        '500':
          description: Internal Server Error
  /v1/admin/users:
    post:
      security: 
        - cookieAccessToken: []
        - headerAccessToken: []
      tags:
        - admin
      summary: Create new user
      description: Creates a new user
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/CreateUserRequest'
      responses:
        '201':
          $ref: '#/components/responses/SuccessCreateUserResponse'
        '400':
          $ref: '#/components/responses/BadRequestCreateUserResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
    get:
      security:
        - cookieAccessToken: []
        - headerAccessToken: []
      tags:
        - admin
      summary: List users
      description: List and paginate users
      operationId: listUsers
      parameters:
        - $ref: '#/components/parameters/PageQueryParameter'
        - $ref: '#/components/parameters/SizeQueryParameter'
        - $ref: '#/components/parameters/UsernameQueryParameter'
        - $ref: '#/components/parameters/EmailQueryParameter'
        - $ref: '#/components/parameters/EnableQueryParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessUsersListResponse'
        '400':
          $ref: '#/components/responses/BadRequestCreateUserResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
  
  /v1/admin/users/{userId}:
    get:
      tags:
        - admin
      summary: Get user by user id
      description: ''
      operationId: getUserById
      parameters:
        - $ref: '#/components/parameters/UserIdPathParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessUserProfileResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      tags:
        - admin
      summary: Update user
      description: Updates user data
      operationId: updateUser
      parameters:
        - $ref: '#/components/parameters/UserIdPathParameter'
      requestBody:
        $ref: '#/components/requestBodies/UpdateUserRequest'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequestCreateUserResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '409':
          description: Conflict
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
    delete:
      tags:
        - admin
      summary: Delete user
      description: Delete user
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/UserIdPathParameter'
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
        
components:
  schemas:
    UpdateProfileRepresentation:
      type: object
      properties:
        username:
          type: string
          example: coolusername
    TokenRepresentation:
      type: object
      properties:
        accessToken:
          type: string
          example: 'abcdef1233'
        refreshToken:
          type: string
          example: 'abcdef1233'
    LoginRepresentation:
      type: object
      properties:
        response_type:
          type: string
          enum: ['code', 'token']
        mfa_token:
          type: string
    ApiErrorException:
      type: object
      properties:
        code:
          type: string
          example: 'ERR010'
        message:
          type: string
          example: 'Field username must not be null or empty'
        traceId:
          type: string
          example: 'df438c36-9aa4-11ed-a8fc-0242ac120002'
    UserRepresentation:
      type: object
      properties:
        userId:
          type: string
          example: c223a9f5-7174-4102-aacc-73f03954dde8
        username:
          type: string
          example: cool_username
        isMfaEnabled:
          type: boolean
        isMfaVerified:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateUserRepresentation:
      type: object
      properties:
        username:
          type: string
          example: johndoe
        password:
          type: string
          example: super-secret-password
        roles:
          type: array
          items:
            type: string
          example: ['admin', 'admin/user-creation']
    PageRepresentation:
      type: object
      properties:
        size:
          type: integer
          example: 10
        totalElements:
          type: integer
          example: 10
        page:
          type: integer
          example: 1
        next:
          type: string
          example: 'http://localhost:9000/users?page=2&size=10'
    UpdateUserRepresentation:
      type: object
      properties:
        enabled:
          type: boolean
        mfaEnabled:
          type: boolean
        username:
          type: string
          example: new-username
  
  parameters:
    UsernameQueryParameter:
      name: username
      in: query
      schema:
        type: string
        example: johndoe
    EmailQueryParameter:
      name: email
      in: query
      schema:
        type: string
        example: john.doe@mail.com
    EnableQueryParameter:
      name: enabled
      in: query
      schema:
        type: boolean
        example: true
    PageQueryParameter:
      name: page
      required: true
      in: query
      schema:
        type: integer
        example: 1
    SizeQueryParameter:
      name: size
      required: true
      in: query
      schema:
        type: integer
        example: 1
    UserIdPathParameter:
      name: userId
      in: path
      description: 'The userId that needs to be fetched.'
      required: true
      schema:
        type: string
        example: 507f1f77bcf86cd799439011
          
  requestBodies:
    UpdateProfileRequest:
      description: User request object required to update a existing user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateProfileRepresentation'
    LoginRequest:
      description: login request body
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/LoginRepresentation'
    CreateUserRequest:
      description: User request object required to create a new user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateUserRepresentation'
    UpdateUserRequest:
      description: Update user request object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateUserRepresentation'
  
  responses:
    SuccessLoginResponse:
      description: login request returns with status success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenRepresentation'
            
    BadRequestLoginResponse:
      description: payload invalid or malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorException'
    
    SuccessRefreshResponse:
      description: refresh request returns with status success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenRepresentation'
    
    SuccessUserProfileResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRepresentation'

    BadRequestCreateUserResponse:
      description: payload invalid or malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorException'
    
    SuccessCreateUserResponse:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRepresentation'
    
    SuccessUsersListResponse:
      description: List of user object
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/PageRepresentation'
              - type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserRepresentation'
  
  securitySchemes:
    loginAuth:
      type: http
      scheme: basic
    cookieAccessToken:
      type: apiKey
      in: cookie
      name: access_token
    headerAccessToken:
      type: apiKey
      in: header
      name: Authorization
    cookieRefreshToken:
      type: apiKey
      in: cookie
      name: refresh_token