name: Go package
on:
  push:
    paths:
    - 'raspstore-api/**'
jobs: 
  raspstore-api-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: sudo apt-get install libpam0g-dev

      - name: Test
        working-directory: raspstore-api
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          working-directory: raspstore-api
          version: v1.54
