name: Go package
on:
  push:
    paths:
    - 'application/file-info-service/**'
jobs: 
  file-info-service-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Build
        working-directory: ./application/file-info-service
        run: go build

      - name: Test
        working-directory: ./application/file-info-service
        run: go test ./test/...
