name: Go package
on:
  push:
    paths:
    - 'file-service/**'
jobs: 
  file-info-service-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        working-directory: file-service
        run: go test -v ./tests/...

      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          working-directory: file-service
          version: v1.54