name: Go package
on:
  push:
    paths:
    - 'application/fs-service/**'
jobs: 
  fs-service-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Build
        working-directory: ./application/fs-service
        run: go build

      - name: Test
        working-directory: ./application/fs-service
        run: go test ./test/...
